### ISSUE TITLE
outdoor 运行错误

### ISSUE THREAD

**Issue by mengxzh15** [liboyun/ZID#1]
当数据SOTS为户外数据时，会报错:
RuntimeError: size mismatch, m1: [1 x 32768], m2: [25088 x 100] at /opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/THC/generic/THCTensorMathBlas.cu:273

**Comment by liboyun** [comment]
你好，你可以试着把dehazing.py的233行中prepare_gt_img函数的SOTS参数设成False试一下。因为SOTS室内数据的gt有白边，所以当时写了这个参数来把白边裁掉，而SOTS室外数据的gt里面没有白边，所以会造成gt和hazy图片大小不一致出错。
