### ISSUE TITLE
PSNR

### ISSUE THREAD

**Issue by li-2019** [liboyun/ZID#2]
你好，我在dehazing.py中测试HSTS中10张合成雾图的时候，得到的PSNR低于论文中给出的值，不知道哪里出问题了？

**Comment by liboyun** [comment]
同学你好，由于模型初始化等原因，每次ZID的PSNR值会在21-23之间有一定的波动，您可以试着多运行几次，应该就能获得论文中报道的结果

**Comment by li-2019** [comment]
好的,感谢回复。
